### ISSUE TITLE
een sectorplotset moet een functie krijgen die een time of cmtime teruggeeft

### ISSUE THREAD

**Issue by rduivenvoorde** [rduivenvoorde/sectorplot#1]
Om in de openingsdialoog de sectorsets te kunnen toneen met savetime en countermeasuretime.
Moet de sectorset die terug kunnne geven:

Ik ga zoiets gebruiken: 

save_time = QStandardItem(sectorplot_set.saveTime())
countermeasure_time = QStandardItem(sectorplot_set.counterMeasureTime())

dus OF meteen de juiste string teruggeven, <= mijn voorkeur
OF een object teruggeven waar ik eenvoudig een string aan kan vragen (rekening houdend met locale/taal/timezone etc. Zou dan ws een Qt object moeten zijn

**Comment by raymondnijssen** [comment]
get_save_time_string()
and
get_counter_measure_time_string()
